# Generated by Django 4.2.5 on 2023-12-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date',
        ),
    ]
